#include "../../../engine/assets/shaders/bindless/base.glsl"
#include "../../../engine/assets/shaders/bindless/transform.glsl"
#include "../../../engine/assets/shaders/bindless/camera.glsl"
#include "../../../engine/assets/shaders/bindless/mesh.glsl"
#include "../../../engine/assets/shaders/bindless/text.glsl"
