#pragma once

#include <msdfgen/msdfgen.h>
#include <msdfgen/msdfgen-ext.h>

#include <msdf-atlas-gen/types.h>
#include <msdf-atlas-gen/utf8.h>
#include <msdf-atlas-gen/Rectangle.h>
#include <msdf-atlas-gen/Charset.h>
#include <msdf-atlas-gen/GlyphBox.h>
#include <msdf-atlas-gen/GlyphGeometry.h>
#include <msdf-atlas-gen/FontGeometry.h>
#include <msdf-atlas-gen/RectanglePacker.h>
#include <msdf-atlas-gen/rectangle-packing.h>
#include <msdf-atlas-gen/Workload.h>
#include <msdf-atlas-gen/size-selectors.h>
#include <msdf-atlas-gen/bitmap-blit.h>
#include <msdf-atlas-gen/AtlasStorage.h>
#include <msdf-atlas-gen/BitmapAtlasStorage.h>
#include <msdf-atlas-gen/TightAtlasPacker.h>
#include <msdf-atlas-gen/AtlasGenerator.h>
#include <msdf-atlas-gen/ImmediateAtlasGenerator.h>
#include <msdf-atlas-gen/DynamicAtlas.h>
#include <msdf-atlas-gen/glyph-generators.h>
#include <msdf-atlas-gen/image-encode.h>
#include <msdf-atlas-gen/image-save.h>
#include <msdf-atlas-gen/artery-font-export.h>
#include <msdf-atlas-gen/csv-export.h>
#include <msdf-atlas-gen/json-export.h>
#include <msdf-atlas-gen/shadron-preview-generator.h>
